<?php
?>
<h1>Scari, Trepte si Balustrade de Stejar</h1>
<h4>Venim in intampinarea clientilor care doresc sa creeze un mediu complet si uniform avand trepte, balustrade, plinta si alte element din camera construite din acelasi material. Impreuna cu dvs putem crea diverse elemente pentru a imbraca treptele in parchet din stejar, pentru a crea elemente decorative si va putem asista inclusiv cu fabricarea cadrelor pentru usi din acelasi material.
</h4>
<h4>Linia noastra include 3 modele de plinta standard, facute dupa modelul englezesc: Bullnose, Ogee si Chamfered. Elementele care completeaza treptele cum ar fi balustradele, pot fi construite in totalitate din stejar sau va putem oferi elementele necesare pt a completa design-ul dvs.
</h4>
<?php
?>
